### ISSUE TITLE
Don't insert <br> on new lines when syncing markdown

### ISSUE THREAD

**Issue by keturiosakys** [readmeio/markdown#689]
**Context**: we sync all of our documentation from Github repos, using the full suite of `rdme` tools: both OpenAPI spec and docs written in markdown. We intentionally do not use ReadMe's live editor to maintain a single source of truth in a repo that can have automated checks and sync up.

**Problem**:

Most of the markdown rendering tools follow the spec that insert a new line only after a blank line was inserted in source.

For example:
```markdown
If I write some text here even if I insert a new line
here it, in the final output it will continue on the same line

And only here it will get a new line/paragraph
```

However, ReadMe will render all of the `\n` in the upload and break lines creating a somewhat disorienting output.

**Comment by kellyjosephprice** [comment]
We made the decision to treat newlines in a non-standard way. We were thinking it's more intuitive for some people if newlines are preserved, and matches more with how text editors behave. [Here's where the option](https://github.com/readmeio/markdown/blob/next/options.js#L5) is defined.

If you'd like to use the standard behavior, feel free to get in touch at [support@readme.io](mailto:support@readme.io) and we can toggle a flag at the project level for you.

**Comment by keturiosakys** [comment]
understood, thank you - appreciate the response!

**Comment by jaseemabid** [comment]
@kellyjosephprice Thank you for clarifying this. 

Would it be possible to make this something users can configure themselves? Either through web UI or rdme cli?

I'll reach out to support in the meanwhile.

**Comment by martin-cod** [comment]
I wnat to highlight it once again. It is not clear what was the reason of taking a decision not to follow. Discussing the topic of "new linse" we shoulpd split itnto two different branches:
1. Instert a new line `<br>` tag
2. Put text into paragraph `<p>` tag

For new lines in Markdown basic syntax end a line with two or more spaces:

```markdown
This is the first line.  
And this is the second line.
```

---
This is the first line.  
And this is the second line.

---

For paragraps use a blank line to separate one or more lines of text

```markdown
This is your first paragraph.

And this is the second one.
```

---
This is your first paragraph.

And this is the second one.

---

### Suggestion for Readme online editor

#### New lines

Insert a new line when _Cmd + Return_ buttons are clicked. **In Raw Mode, the carrege return symbol will be converted into two spaces in the end of line**.

The change in **bold** is what can be modified in current Readme implementation. Please note, that it will not break existing text, if users have a configuration they can chage themselves.

#### Paragraphs
Insert a new paragraph when _Return_ button is clicked. In Raw Mode, it will be converted to an empty text line.

This is how Readme currently works.

**Comment by kellyjosephprice** [comment]
> Insert a new line when _Cmd + Return_ buttons are clicked. **In Raw Mode, the carrege return symbol will be converted into two spaces in the end of line**.

You can do this now with `shift+return`!

**Comment by martin-cod** [comment]
That's great, @kellyjosephprice! It works in the following scenarios:

**Scenario: Display "new line" on `Shift + Enter`**
Given user is in "Editor mode"  
And he is writing a line of text
When `Shift + Enter` is clicked 
Then it displays a new line after a line of text in "Editor Mode"
And it displays `<br>` in HTML (when previewing the page)
And it displays "two spaces +  carrege return" symbols in "Raw mode" (when switching to "Raw mode")

**Scenario: Display "new line" when line ending with `two spaces + carrege return` symbols**
Given user is in "Raw mode"
And line is ending with `two spaces + carrege return` symbols
And text is the following
```markdown
There are two spaces in the end of the line  
So that you see this line of text on a new raw
```
When swithing to "Editor Mode"
Then it displays new line in "Editor Mode"
And it displays `<br>` in html (when previewing the page)

But it fails in the following scenario

**Scenario: Do not display "new line" when line ending with only `carrege return` symbol  (Raw Mode)**
Given user is in "Raw mode"
And line is ending with `carrege return` symbol
And there are no `two spaces` before  `carrege return` in the end of line
And text is the following
```markdown
There are NO spaces in the end of the line.
So that this part of text should be a continuation of the previouse line
```
When swithing to "Editor Mode"
Then it displays a single line in "Editor Mode"
And it displays  a single line in html (there is no `<br>` tag between markdown lines)


Currently the scenario **Do not display "new line" when line ending with only `carrege return` symbol  (Raw Mode)** behaves in the following way:

When swithing to "Editor Mode"
Then it displays a new line in "Editor Mode"
When switching back to "Raw Mode"
Then it displays `two spaces +  carrege return` symbols in "Raw mode"

If Readme provides two modes "Raw mode" and "Editor mode" it is reasonable ot ask to support correct formating transition when switching between modes in both ways.

Thanks

**Comment by kellyjosephprice** [comment]
> Currently the scenario **Do not display "new line" when line ending with only `carriage return` symbol (Raw Mode)** behaves in the following way:
> 
> When switching to "Editor Mode" Then it displays a new line in "Editor Mode" When switching back to "Raw Mode" Then it displays `two spaces + carriage return` symbols in "Raw mode"

This should be fixed now!

**Comment by martin-cod** [comment]
> > Currently the scenario **Do not display "new line" when line ending with only `carriage return` symbol (Raw Mode)** behaves in the following way:
> > When switching to "Editor Mode" Then it displays a new line in "Editor Mode" When switching back to "Raw Mode" Then it displays `two spaces + carriage return` symbols in "Raw mode"
> 
> This should be fixed now!

It is still not fixed
https://app.screencast.com/tp595HQ3aYpmW

**Comment by kellyjosephprice** [comment]
> It is still not fixed https://app.screencast.com/tp595HQ3aYpmW

I know it's a divisive choice, but that was by intention. See my previous comment: https://github.com/readmeio/markdown/issues/689#issuecomment-1431800943

> We made the decision to treat newlines in a non-standard way. We were thinking it's more intuitive for some people if newlines are preserved, and matches more with how text editors behave. [Here's where the option](https://github.com/readmeio/markdown/blob/next/options.js#L5) is defined.
>
> If you'd like to use the standard behavior, feel free to get in touch at [support@readme.io](mailto:support@readme.io) and we can toggle a flag at the project level for you.

We may be able to get rid of that completely in the future, but for now, you'd have to ask support for to turn it off.

Sorry!
